In [16]:
import os
import numpy as np
import matplotlib as plt
import cv2
from glob import glob
from skimage.measure import label, regionprops, find_contours


In [33]:

images = cv2.imread('aaa.jpg')
roi = cv2.selectROI(images)
cv2.imshow('eee',roi)

error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1267: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'


In [7]:
# """ Creating a directory """
# def create_dir(path):
#     if not os.path.exists(path):
#         os.makedirs(path)

# """ Convert a mask to border image """
# def mask_to_border(mask):
#     h, w = mask.shape
#     border = np.zeros((h, w))

#     contours = find_contours(mask, 128)
#     for contour in contours:
#         for c in contour:
#             x = int(c[0])
#             y = int(c[1])
#             border[x][y] = 255

#     return border

# """ Mask to bounding boxes """
# def mask_to_bbox(mask):
#     bboxes = []

#     mask = mask_to_border(mask)
#     lbl = label(mask)
#     props = regionprops(lbl)
#     for prop in props:
#         x1 = prop.bbox[1]
#         y1 = prop.bbox[0]

#         x2 = prop.bbox[3]
#         y2 = prop.bbox[2]

#         bboxes.append([x1, y1, x2, y2])

#     return bboxes

# def parse_mask(mask):
#     mask = np.expand_dims(mask, axis=-1)
#     mask = np.concatenate([mask, mask, mask], axis=-1)
#     return mask



In [32]:

# """ Load the dataset """
# im = cv2.imread('x.png', cv2.IMREAD_COLOR)
# masks = cv2.imread('aaa.jpg', cv2.IMREAD_GRAYSCALE)
# print(im)


[[[133 115 102]
  [133 115 102]
  [134 110 114]
  ...
  [131 167 209]
  [128 158 210]
  [124 154 206]]

 [[132 116 103]
  [130 114 101]
  [132 108 112]
  ...
  [138 161 214]
  [129 155 208]
  [123 149 202]]

 [[127 112 110]
  [126 111 109]
  [131 107 111]
  ...
  [137 162 217]
  [128 158 210]
  [122 152 204]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 251]
  ...
  [137 143 174]
  [127 135 166]
  [127 135 166]]

 [[255 255 255]
  [255 255 255]
  [255 255 252]
  ...
  [128 133 166]
  [121 128 161]
  [115 122 155]]

 [[255 255 255]
  [255 255 255]
  [255 255 251]
  ...
  [120 125 156]
  [118 119 150]
  [114 115 147]]]


In [23]:
 
contours, hierarchy = cv2.findContours(masks,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)[-2:]
idx =0 
for cnt in contours:
    idx += 1
    x,y,w,h = cv2.boundingRect(cnt)
    roi=im[y:y+h,x:x+w]
    cv2.imwrite(str(idx) + '.jpg', roi)
    #cv2.rectangle(im,(x,y),(x+w,y+h),(200,0,0),2)


In [29]:

cv2.waitKey(0)

error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1267: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'
